#Exercise 7: merging data sets & practicing working with data sets

#functions (library)
  #merge (base)
  #join function family (dplyr)

#load libraries----
library(tidyverse)
library(stringr)

#functions -----
clean.quotes <- function(y){
  gsub(pattern = '"', replacement = "", x = y)
}
clean.whitespace<- function(y){
  gsub(pattern = ' ', replacement = "", x = y)
}

'%!in%' <- function(x,y)!('%in%'(x,y)) #custom operator to find columns that are not in a data frame
#-----

# GOAL: Your goal is to merge the 'starec', 'envrec' and 'aurelia' data so you can evaluate what environmental parameters may vary
# with jellyfish (Aurelia) biomass (later on in class).


#import the "STAREC_rev20190402.csv" file. You will need to use the following arguments:
# quote="", sep = ",", check.names=T, header = T, stringsAsFactors = F, fill=T

s <- read.csv(file = "data_sets/e7_seamap_data/STAREC_rev20190402.csv", quote="",
              sep = ",", check.names=T, header = T, stringsAsFactors = F, fill=T)

  #clean up column headers
  #remove the 'X.' from the column headers and make the names lowercase
  names(s) <- gsub(pattern = "X.", replacement = "", x = names(s))
  names(s) <- tolower(names(s))

  #run this to finish the clean-up
  names(s) <- gsub("\\.", "", names(s))

  ## use the 'sapply' function to clean up the data
  ## link to examples
  browseURL("https://www.guru99.com/r-apply-sapply-tapply.html#:~:text=vertigo%22%20%22chinatown%22-,sapply()%20function,function%20but%20returns%20a%20vector.")

  #clean quotes off of data using the 'clean.quotes' function
  s[] <- sapply(X = s, FUN = clean.quotes)

  # 'clean.whitespace' off of the values in the 'gears' column
  s$gears <- sapply(X = s$gears, FUN = clean.whitespace)

#convert columns that store numbers but are character into numeric data type
#workflow: extract columns that are suppose to be characters, convert the other columns to numbers and
# then put them back in the data frame

  #extract the columns that are supposed to be characters
  char_cols <- s[,c("s_sta_no","time_emil","mo_day_yr","start_date","end_date","s_lath","s_lonh","e_lath",
                    "e_lonh","gears","haulvalue","data_code","dbtype","x")]
  names_char_cols <- names(char_cols)

# subset the columns that are suppose to be numbers by excluding the list of character columns (i.e., 'names_char_cols') from the
# 's' data frame column names

  # in other words, subset the vector generated by 'names(s)' to find the values NOT found in the vector 'names_char_cols'
  # on lines 38-39
  to.num.cols <- names(s)[which(names(s) %!in% names_char_cols)]

  #use the 'lapply' function to go through the data frame columns that need to be numbers and apply the 'as.numeric' function
  s[to.num.cols] <- lapply(X = s[to.num.cols], FUN = as.numeric) #there will be warnings of NAs; this is okay

  #check your work; are the data frame's data types numeric?
  str(s)

  #There are three columns with date-time information in the 'starec' data frame: start_date, end_date & mo_day_yr.
  #convert the data type of these columns to a object that has a 'date time' class

  s$start_date <- as.POSIXct(strptime(x = s$start_date, format = "%Y-%m-%d %H:%M:%S"))
  s$end_date <- as.POSIXct(strptime(x = s$end_date, format = "%Y-%m-%d %H:%M:%S"))
  s$mo_day_yr <- as.POSIXct(strptime(x = s$mo_day_yr, format = "%Y-%m-%d"))

  starec <- s; rm(s)

#read in the 'envrec.csv' file ----

e <- read.csv(file = "data_sets/e7_seamap_data/ENVREC.csv", header = T, stringsAsFactors = F)

#keep columns 1:31 and make all the column names be lower-case
e <- e[,names(e)[1:31]]
names(e) <- tolower(names(e))

#merge the 'starec' and 'envrec' data frames using common column names 'stationid', 'cruiseid', 'cruise_no', and 'vessel'.
# Be mindful that the data frames have a different number of rows.

se <- merge(x = e, y = s, by=c("stationid","cruiseid","vessel","cruise_no"), all.x = T)

#there are quite a few columns here that are not germane (e.g., stat_zone) to our overall goal. Subset the merged data frame to
#keep the following columns:

  se_evar <- se[,c(1:4,13:31,43,53:57)]

  #reorder the columns so that the 'mo_day_yr' is the first column in the data frame
  se_evar <- se_evar[,c(24, 1:23,25:length(se_evar))]

#load the aurelia data set

  load("data_sets/e7_seamap_data/aurelia_15minCell_statareas.Rdata")

  #filter the 'Aurelia' data set to keep the following columns
  col2keep <- names(a)[c(5:16,18)]

  a <- a[,col2keep]

# Take a look at the columns in the merged 'starec+envrec' and 'a' data frames.
  # What column names do you think are likely to be a 'key' between them. In other words,
  # which column is common between them that could be used to merge observations correctly?

  # using the 'merge' function, combine the 'aurelia' and 'evironmental records (envrec)' data sets. Be mindful that
  # the data sets have a different number of rows.

  ase <- merge(x = a, y = se_evar, by = "stationid", all.x = T)


  #repeat combining the data frames using the followwing functions from the 'join' family. In a comment, tell me how the outcomes differ?
  #Here is a good reference if you need some definitions:
  browseURL("https://dplyr.tidyverse.org/reference/join.html")

  inner_join()

  left_join()

  semi_join()

  #calculate the annual mean number of jellyfish and minimum oxygen concentration at depth (oxymax) along the Louisiana shelf
  #Hints: (1) consider subsetting the columns of interest before summarizing the data; (2) you may need to detach the plyr package

  j <- ase[,c("year","subregion_alongshore","subregion_depth",'use_biomass_den_kg_m2',"oxymax")]
  jsl <- j[j$subregion_alongshore=="2_Lou" & j$subregion_depth == "2_shelf",]
  jsl <- na.omit(jsl)

  detach("package:plyr")
  library(dplyr)
  jam <- jsl %>% group_by(year) %>% summarise(mean.biomass = mean(use_biomass_den_kg_m2), mean.oxy = mean(oxymax))

  #plot the result

  #data = the data frame object created when you summarised by year
  p <- ggplot(data = jam) +
    #x = year; y=1st variable to plot on the y-axis
    geom_line(aes(x = year, y = mean.biomass*100), color='firebrick', size=1) +
    #x = year; y=2nd variable to plot on the y-axis
    geom_line(aes(x = year, y = mean.oxy-3.5), color='steelblue4', size = 1) +
    #code to adjust the x-axis
    scale_x_continuous(name = "",breaks = seq(from = min(jam$year), max(jam$year), 2)) +
    #code to adjust the y-axis
    scale_y_continuous(name = "", breaks = seq(0,3,0.25), expand = c(0,0)) +
    #make the plot aesthetics clean & simple
    theme_classic()
